language: python

env:
  global:
    - ARDUINO_IDE_VERSION='1.0.5'

before_script:
- curl -s http://arduino.googlecode.com/files/arduino-${ARDUINO_IDE_VERSION}-linux64.tgz | sudo tar xz -C /opt

script:
- ls -l /opt
